# Wazuh Certificate Generator
# Run: docker compose -f generate-certs.yml run --rm generator
services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.3
    hostname: wazuh-certs-generator
    environment:
      - CERT_TOOL_VERSION=4.14
    volumes:
      - ./config/certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml
